# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["Lab5"]


jobs:
  # Single deploy job since we're just deploying
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: home562576484.1and1-data.host
          username: ${{secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          local_path: './*'
          remote_path: './afs/umbc.edu/users/s/u/surreyc1/pub/Lab5'
          sftp_only: true

